Update analyze.yml

diff --git a/.github/workflows/analyze.yml b/.github/workflows/analyze.yml
--- a/.github/workflows/analyze.yml
+++ b/.github/workflows/analyze.yml
@@ -54,7 +54,7 @@ jobs:
 
       - name: Comment PR
         if: always()
-        uses: thollander/actions-comment-pull-request@v3
-        with:
-          message: 'Test!'
+        run: |
+          echo "Test!"
+          exit 1  # Fails the workflow with the error message
       
